FROM node:22-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app
USER node

CMD ["sh", "-c", "npm install && npm run dev -- --host"]