volumes:
  frontend-node-modules:
  api-node-modules:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    user: "node"
    volumes:
      - ./frontend/app:/home/node/app
      - ./shared/types:/home/node/app/shared/types
      - frontend-node-modules:/home/node/app/node_modules
    ports:
      - "5173:5173"

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    user: "node"
    volumes:
      - ./backend/api/app:/home/node/app
      - ./shared/types:/home/node/app/shared/types
      - api-node-modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

networks:
  default:
    name: myapp-network